server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://10.5.50.30:3306/auntie-cms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
